### ISSUE TITLE
[BUG] Docker V4 版本开始无法快速登录

### ISSUE THREAD

**Issue by yuuki-nya** [NapNeko/NapCatQQ#636]
### 系统版本

Ubuntu 24.04

### QQNT 版本

9.9.16-29927

### NapCat 版本

4.2.35

### OneBot 客户端

nonebot

### 发生了什么?

这是docker-compose.yml
```yaml
services:
    napcat-123456789: 
        environment:
            - ACCOUNT=123456789            
            - NAPCAT_UID=${NAPCAT_UID}
            - NAPCAT_GID=${NAPCAT_GID}            
        container_name: napcat-123456789
        volumes:
            - ./data/123456789:/app/.config/QQ
            - ./config:/app/napcat/config          
        restart: always
        image: mlikiowa/napcat-docker:v4.2.35
```
启动，扫码登录后，正常登录，但是重启容器，就需要重新扫码登录了。
此时，我将`image: mlikiowa/napcat-docker:v4.2.35`更换为`image: mlikiowa/napcat-docker:v3.7.0`，其他不动，`docker-compose up -d`重建项目，该号码就正常重新登录了，不需要重新扫码，重启容器也没有任何问题

### 如何复现

1. 使用docker镜像v4版本
2. 固化目录
3. 将镜像换回v3版本正常

### 期望的结果?

docker镜像v4版本可以正常快速登录

**Comment by MliKiowa** [comment]
固定mac

**Comment by yuuki-nya** [comment]
固化过了，这是完整的yml
```yaml
services:
    napcat-123456789: 
        environment:
            - ACCOUNT=123456789            
            - NAPCAT_UID=${NAPCAT_UID}
            - NAPCAT_GID=${NAPCAT_GID}            
        container_name: napcat-123456789
        volumes:
            - ./data/123456789:/app/.config/QQ
            - ./config:/app/napcat/config          
        restart: on-failure:3
        image: mlikiowa/napcat-docker:v4.2.35
        mac_address: a6:8a:11:5c:95:02
        networks:
            custom_network:
                ipv4_address: 172.30.3.3            

networks:
    custom_network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.30.3.0/24
```
