### ISSUE TITLE
[BUG] 当webui.json的值是由ConfigMap设置时，会导读配置设置错误

### ISSUE THREAD

**Issue by wu-yafeng** [NapNeko/NapCatQQ#669]
### 系统版本

K8S-Docker

### QQNT 版本

mlikiowa/napcat-docker:latest

### NapCat 版本

mlikiowa/napcat-docker:latest

### OneBot 客户端

mlikiowa/napcat-docker:latest

### 发生了什么?

napcat无法从只读文件中加载webui.json配置

### 如何复现

1. 创建ConfigMap

``` yaml
apiVersion: v1
data:
  'v1': |-
    {
        "host": "0.0.0.0",
        "port": 6099,
        "prefix": "/v1",
        "token": "mytoken",
        "loginRate": 3
    }
kind: ConfigMap
metadata:
  namepsace: default
```
2. 创建Deployment:

``` yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: napcat
  name: napcat-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: napcat
  template:
    metadata:
      labels:
        app: napcat
      namespace: default
    spec:
      containers:
        - image: mlikiowa/napcat-docker:latest
          imagePullPolicy: IfNotPresent
          name: container-0
          ports:
            - containerPort: 6099
              name: webui
              protocol: TCP
            - containerPort: 3000
              name: onebot-api
              protocol: TCP
          volumeMounts:
            - mountPath: /app/napcat/config/webui.json
              name: vol-adxgh
              subPath: 'v1'
      volumes:
        - configMap:
            defaultMode: 511
            name: napcat-webui-config
          name: vol-adxgh

```

### 期望的结果?

在文件只读的情况下，依然可以加载webui.json配置

### NapCat 运行日志

```shell
读取配置文件失败 Error: EROFS: read-only file system, open '/app/napcat/config/webui.json'
    at async open (node:internal/fs/promises:636:25)
    at async Object.writeFile (node:internal/fs/promises:1216:14)
    at async WebUiConfigWrapper.GetWebUIConfig (file:///app/napcat/napcat.mjs:55439:9)
    at async InitWebUi (file:///app/napcat/napcat.mjs:55946:18) {
  errno: -30,
  code: 'EROFS',
  syscall: 'open',
  path: '/app/napcat/config/webui.json'
}
```
